// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Healtcheck.proto

#define PROTOBUF_INLINE_NOT_IN_HEADERS 0

#pragma warning(disable:4100)
#pragma warning(disable:4127)
#pragma warning(disable:4125)
#pragma warning(disable:4267)
#pragma warning(disable:4389)
#pragma warning(disable:4800)
#pragma warning(disable:4946)
#pragma warning(disable:4668)
#pragma warning(disable:4582)
#pragma warning(disable:4583)


#include "Healtcheck.pb.h"
#include "Healtcheck.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace utility_messages {

static const char* HealthcheckService_method_names[] = {
  "/utility_messages.HealthcheckService/RunCheck",
};

std::unique_ptr< HealthcheckService::Stub> HealthcheckService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthcheckService::Stub> stub(new HealthcheckService::Stub(channel));
  return stub;
}

HealthcheckService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RunCheck_(HealthcheckService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthcheckService::Stub::RunCheck(::grpc::ClientContext* context, const ::utility_messages::HealthCheckParams& request, ::utility_messages::HealthcheckResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RunCheck_, context, request, response);
}

void HealthcheckService::Stub::experimental_async::RunCheck(::grpc::ClientContext* context, const ::utility_messages::HealthCheckParams* request, ::utility_messages::HealthcheckResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RunCheck_, context, request, response, std::move(f));
}

void HealthcheckService::Stub::experimental_async::RunCheck(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::utility_messages::HealthcheckResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RunCheck_, context, request, response, std::move(f));
}

void HealthcheckService::Stub::experimental_async::RunCheck(::grpc::ClientContext* context, const ::utility_messages::HealthCheckParams* request, ::utility_messages::HealthcheckResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RunCheck_, context, request, response, reactor);
}

void HealthcheckService::Stub::experimental_async::RunCheck(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::utility_messages::HealthcheckResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_RunCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::utility_messages::HealthcheckResult>* HealthcheckService::Stub::AsyncRunCheckRaw(::grpc::ClientContext* context, const ::utility_messages::HealthCheckParams& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::utility_messages::HealthcheckResult>::Create(channel_.get(), cq, rpcmethod_RunCheck_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::utility_messages::HealthcheckResult>* HealthcheckService::Stub::PrepareAsyncRunCheckRaw(::grpc::ClientContext* context, const ::utility_messages::HealthCheckParams& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::utility_messages::HealthcheckResult>::Create(channel_.get(), cq, rpcmethod_RunCheck_, context, request, false);
}

HealthcheckService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthcheckService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthcheckService::Service, ::utility_messages::HealthCheckParams, ::utility_messages::HealthcheckResult>(
          std::mem_fn(&HealthcheckService::Service::RunCheck), this)));
}

HealthcheckService::Service::~Service() {
}

::grpc::Status HealthcheckService::Service::RunCheck(::grpc::ServerContext* context, const ::utility_messages::HealthCheckParams* request, ::utility_messages::HealthcheckResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace utility_messages

